In [3]:
import torch
import numpy as np

In [4]:
torch.__version__

'2.0.0+cu118'

In [5]:
#====================================================#
#                Initialize Tensor                   #
#====================================================#

In [6]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'

In [7]:
my_tensor = torch.tensor([[1, 2, 3], [4, 5, 6]], dtype = torch.float32, 
                         device=device, requires_grad=True)
my_tensor

tensor([[1., 2., 3.],
        [4., 5., 6.]], device='cuda:0', requires_grad=True)

In [8]:
print(my_tensor.shape)
print(my_tensor.dtype)
print(my_tensor.device)
print(my_tensor.requires_grad)

torch.Size([2, 3])
torch.float32
cuda:0
True


In [9]:
torch.empty(size=(3, 3))

tensor([[0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 1.1244e-33, 0.0000e+00],
        [5.8046e-35, 0.0000e+00, 5.6768e+32]])

In [10]:
torch.zeros(size = (3, 3))

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [11]:
x = torch.rand(size=(2, 5, 3))
x

tensor([[[0.2567, 0.5799, 0.8325],
         [0.8636, 0.5864, 0.9318],
         [0.4329, 0.1731, 0.8337],
         [0.2909, 0.3370, 0.0359],
         [0.9187, 0.0175, 0.8057]],

        [[0.0483, 0.7646, 0.8031],
         [0.4016, 0.8551, 0.8839],
         [0.4049, 0.5214, 0.8941],
         [0.4715, 0.5780, 0.3683],
         [0.8212, 0.7145, 0.1359]]])

In [12]:
torch.ones_like(x)

tensor([[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]])

In [13]:
torch.eye(4)

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

In [14]:
torch.arange(0, 16, 3)

tensor([ 0,  3,  6,  9, 12, 15])

In [15]:
torch.linspace(0, 12, 5)

tensor([ 0.,  3.,  6.,  9., 12.])

In [16]:
torch.empty((1, 6)).normal_(mean =0, std =1)

tensor([[ 0.0814, -0.8148, -0.4818, -1.4892,  0.7749, -1.5615]])

In [17]:
torch.empty((1, 6)).uniform_(0, 4)

tensor([[2.1990, 0.0587, 3.4862, 3.1042, 1.6524, 0.4310]])

In [18]:
torch.diag(torch.arange(4, 16, 3))

tensor([[ 4,  0,  0,  0],
        [ 0,  7,  0,  0],
        [ 0,  0, 10,  0],
        [ 0,  0,  0, 13]])

In [19]:
# how to initialize and convert tensors to other types(int, float, double)

In [20]:
tensor = torch.arange(4)
print(tensor)
print(tensor.bool())
print(tensor.short())
print(tensor.long().dtype)
print(tensor.half())
print(tensor.float().dtype)

tensor([0, 1, 2, 3])
tensor([False,  True,  True,  True])
tensor([0, 1, 2, 3], dtype=torch.int16)
torch.int64
tensor([0., 1., 2., 3.], dtype=torch.float16)
torch.float32


In [21]:
# array to tensor conversion and vice-versa

In [22]:
np_array = np.zeros((3, 4))
tensor = torch.from_numpy(np_array)
np_back = tensor.numpy()

In [23]:
#====================================================#
#        Tensor Math & Comparison Operations         #
#====================================================#

In [30]:
x = torch.tensor([1, 2, 3])
y = torch.tensor([9, 8, 7])



# Addition
z1 = torch.empty(3)
torch.add(x,y, out=z1)

z2 = torch.add(x, y)

z3 = x + y

# Subtraction 
z = x - y

In [32]:
# Division
print(torch.true_divide(x, y))
print(torch.true_divide(x, 2))

tensor([0.1111, 0.2500, 0.4286])
tensor([0.5000, 1.0000, 1.5000])


In [33]:
# inplace operations (more computationally efficient)
t = torch.zeros(3)
t.add_(x)
t += x 

In [36]:
x.pow(3)
x ** 2

tensor([1, 4, 9])

In [39]:
# Mat Mul
x1 = torch.rand(3, 4)
x2 = torch.rand(4, 2)

torch.mm(x1, x2) ==  x1 @ x2


tensor([[True, True],
        [True, True],
        [True, True]])

In [40]:
mat_exp = torch.rand(5, 5)
mat_exp.matrix_power(2)

tensor([[0.9387, 1.0326, 1.5153, 0.6857, 1.0439],
        [0.4130, 1.0453, 1.0060, 0.7674, 0.7133],
        [0.2877, 0.7005, 0.8249, 0.5755, 0.6459],
        [1.1127, 1.3208, 1.9232, 0.9247, 1.2346],
        [0.6738, 0.7699, 1.1699, 0.5696, 0.8607]])

In [44]:
# element wise 
x * y

tensor([ 9, 16, 21])

In [45]:
# dot product
torch.dot(x, y)

tensor(46)

In [46]:
# Batch Matrix Multiplication

batch = 32
n = 10
m = 20
p = 30

In [50]:
tensor1 = torch.rand((batch, n, m))
tensor2 = torch.rand((batch, m, p))

In [52]:
out_bmm = torch.bmm(tensor1, tensor2) # batch, n, p

In [53]:
# Broadcasting
x1 = torch.rand(5, 5)
x2 = torch.rand(1, 5)

z = x1 - x2